name: Deploy Static Files to EC2

on:
  push:
    branches: [ "main" ] # This workflow triggers on pushes to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest # The job will run on a fresh Ubuntu runner provided by GitHub Actions.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out your repository code into the runner.

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # Configures AWS credentials for interacting with AWS services.
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Your AWS Access Key ID, stored as a GitHub secret.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Your AWS Secret Access Key, stored as a GitHub secret.
          aws-region: ${{ secrets.AWS_REGION }} # Your AWS region, stored as a GitHub secret.

      - name: Prepare flattened static files on runner
        id: prepare_static_files # Assign an ID to this step to reference its outputs later.
        run: |
          # Create a unique temporary directory on the GitHub Actions runner.
          # This is where we'll collect all .css and .js files in a flat structure.
          FLAT_STATIC_DIR=$(mktemp -d)
          echo "Created temporary directory for flattened files on runner: $FLAT_STATIC_DIR"

          # Find all .css and .js files from the entire repository (checked out in current directory)
          # and copy them directly into the FLAT_STATIC_DIR.
          # The -L option for cp ensures symbolic links are followed.
          # If files with the same name exist in different original subdirectories, the last one found will overwrite previous ones.
          find . -type f \( -name "*.css" -o -name "*.js" \) -exec cp -L {} "$FLAT_STATIC_DIR" \;
          
          echo "Files copied to temporary directory:"
          ls -l "$FLAT_STATIC_DIR" # List the files to verify they are flat.

          # Store the full path and the basename of the temporary directory as outputs.
          # These outputs will be used by subsequent steps.
          echo "flat_static_dir=$FLAT_STATIC_DIR" >> $GITHUB_OUTPUT
          echo "temp_dir_basename=$(basename "$FLAT_STATIC_DIR")" >> $GITHUB_OUTPUT

      - name: Ensure /var/www/html directory exists and is writable on EC2
        uses: appleboy/ssh-action@master # Use SSH action to run commands on EC2.
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Ensuring /var/www/html exists and has correct permissions..."
            # Create the directory if it doesn't exist. -p means no error if it exists.
            sudo mkdir -p /var/www/html
            # Change ownership to your SSH user so it has write permissions.
            # Replace ${{ secrets.USERNAME }} with your actual SSH username (e.g., 'ubuntu').
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} /var/www/html
            # Set appropriate permissions for web content (read/execute for others, full for owner).
            sudo chmod -R 755 /var/www/html
            # Clean up existing CSS/JS files in /var/www/html to ensure a fresh deployment.
            echo "Cleaning up existing .css and .js files in /var/www/html..."
            sudo find /var/www/html/ -maxdepth 1 -type f \( -name "*.css" -o -name "*.js" \) -delete

      - name: Copy Flattened Static Files Directory to EC2
        uses: appleboy/scp-action@master # Uses SCP action to securely copy the prepared directory.
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # The 'source' is the *entire temporary directory* created in the previous step.
          # Note: No trailing slash here, so it copies the directory itself into the target.
          source: "${{ steps.prepare_static_files.outputs.flat_static_dir }}"
          target: "/var/www/html" # This will result in a path like /var/www/html/tmp.somerandomchars/
          overwrite: true # Overwrite the temporary directory if it somehow exists.

      - name: Move files and Cleanup on EC2, Restart Nginx
        uses: appleboy/ssh-action@master # Use SSH action to perform final operations on EC2.
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Retrieve the basename of the temporary directory from the previous step's output.
            TEMP_DIR_BASENAME="${{ steps.prepare_static_files.outputs.temp_dir_basename }}"
            # Construct the full path to the temporary directory on the EC2 instance.
            REMOTE_TEMP_DIR="/var/www/html/$TEMP_DIR_BASENAME"

            echo "Moving files from $REMOTE_TEMP_DIR to /var/www/html..."
            # Move all files (not subdirectories) from the temporary directory into /var/www/html.
            # The 'mv "$REMOTE_TEMP_DIR"/* /var/www/html/' command moves all contents.
            sudo mv "$REMOTE_TEMP_DIR"/* /var/www/html/

            echo "Removing temporary directory $REMOTE_TEMP_DIR..."
            # Remove the now-empty temporary directory.
            sudo rm -rf "$REMOTE_TEMP_DIR"

            echo "Clearing Nginx cache..."
            sudo rm -rf /var/cache/nginx/*

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            echo "Reloading Nginx configuration..."
            sudo systemctl reload nginx 

      - name: Wait for deployment
        run: |
          echo "Waiting 10 seconds for Nginx to settle..."
          sleep 10